### ISSUE TITLE
Style Guide?

### ISSUE THREAD

**Issue by supertylerc** [aker-gateway/Aker#13]
Hi!

I was wondering if there is a specific style guide that should be followed.  While making changes to a local copy to support #11 and #12, my linting plugins raised a large number of issues (tabs, line length).  If I should disable them, I can do that.  If you're interested in bringing the codebase in line with Python's various style guides (pep8, pep257, etc), I could submit a pull request for that.

Thank you!

**Comment by anazmy** [comment]
Lazy me-- I was intending to have style brushed at some point, please feel free to submit a PR for that. 

Many thanks!

**Comment by anazmy** [comment]
A lot of pep8 clean up applied now.
