### ISSUE TITLE
Reload Config File

### ISSUE THREAD

**Issue by supertylerc** [aker-gateway/Aker#19]
It would be really cool if Aker could reload the configuration from disk.  Right now, if I need to modify the list of hosts, I would need to stop and start the `aker.py` process (in other words, log out and log back in).

It would be nice if I could just press `F5` while at the main Aker menu and have it reload the config from disk.

**Comment by anazmy** [comment]
I'm considering F5 to reload list of hosts for different reasons , specially in freeipa branch to query LDAP for an update, I will include this functionality also in master branch .

**Comment by anazmy** [comment]
Refreshing hosts applied
