### ISSUE TITLE
Support "Global" Hosts

### ISSUE THREAD

**Issue by supertylerc** [aker-gateway/Aker#20]
It looks like hosts right now are defined per-user.  This results in duplicating entries quite a bit.  If I have five people on my team and we are managing a total of 500 nodes, I have to have 2,500 hosts in `aker.ini` -- the same 500 for each user.

I would like the ability to label hosts at a more "global" level.  In this particular feature, we would just have a list of 500 hosts.  Ideally, there would be a lookup hierarchy so that an individual user could potentially have the same host as described at the "global" level but with "more specific" information.

**Comment by anazmy** [comment]
usergroups and hostgroups association is one of the main reasons of using freeipa branch, it will support this feature and much much more in a centralized fashion, please consider checking the freeipa branch.

I'm working on an ansible playbook to easy up the installation of the environment for everyone .
