### ISSUE TITLE
Still some small errors in readme.md

### ISSUE THREAD

**Issue by Ramshield** [aker-gateway/Aker#39]
Hi @anazmy.
Just deployed a new Aker server. 

In the readme it says to install redis via yum. But you do this via the pip command? So scrap that I think? 
Also, it didn't want to install Paramiko, I was still missing python-devel, libevent-devel, `error: command 'gcc' failed with exit status 1`.
After installing that it installed Paramiko. 

Also, pip doesn't come by default with CentOS 7 minimal, I used `curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"` and then `python get-pip.py`!

**Comment by anazmy** [comment]
Let me test on a vanilla centos-7 install and see if anything missed , thanks a lot for your feedback !

**Comment by anazmy** [comment]
thanks @Ramshield I modified the readme now , closing this issue
