### ISSUE TITLE
get Name or service not known

### ISSUE THREAD

**Issue by leochan007** [aker-gateway/Aker#46]
TUI show the hosts correctly. but after pressing the "enter" key. get this error below.

File "/opt/aker/SSHClient.py", line 68, in connect
    self._socket.connect((ip, port))
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.gaierror: [Errno -2] Name or service not known

is this DNS issue?

**Comment by anazmy** [comment]
You're right that's Dns, you can use /etc/hosts if you don't have a working nameserver

**Comment by anazmy** [comment]
closing this for now as answer been provided.
