### ISSUE TITLE
No module named 'pyhbac'

### ISSUE THREAD

**Issue by ghost** [aker-gateway/Aker#50]
Hi,
when I tried to run `aker.py` I got 
```
ModuleNotFoundError: No module named 'pyhbac'
```
I believe it is some FreeIPA dependency. I would prefer to be independent on FreeIPA since I do not want to use it anyway. It should be only optional dependency.

**Comment by anazmy** [comment]
Hey,
ur right that's FreeIPA dependency, but its optional, you can just change default identity provider `idp` setting in `aker.ini` to `idp = Json` to use the json instead.

**Comment by ghost** [comment]
Ok, but shouldn't be `Json` provider default since FreeIPA is optional?

**Comment by anazmy** [comment]
For now FreeIPA is the default since its feature complete, i.e. you manage sudo rules,ssh keys and HBAC in centralized way, which is nice specially for large environments.

Also, CRUD functionality for json, i.e. create, read, update, and delete records is not there yet.

**Comment by ghost** [comment]
Ok, thanks. Closing this one.
