### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ghost** [aker-gateway/Aker#52]
Hi, any reason why is this licensed under AGPL-3.0 and not just MIT?

**Comment by anazmy** [comment]
I'm not a legal guy, but AFAIU MIT can allow inclusion of the project in proprietary software, and I didn't want that.

**Comment by ghost** [comment]
Aha, so you want this to be used in open-source projects only? Do I got it right?

**Comment by anazmy** [comment]
Exactly, if I understood MIT license terms correctly.

**Comment by ghost** [comment]
Ok, thanks for clarification.
