### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by ghost** [aker-gateway/Aker#53]
Would you be against using Python3 for this? Python2 is about to be history.

**Comment by anazmy** [comment]
ur absolutely true, when I started this I looked for the common denominator between distros and it was python2.

And I think the project can be converted easily to python3

**Comment by ghost** [comment]
Ok, next time I do something, I will make sure it is Python3 oriented. When I have time, I will review the code and refactor it.

**Comment by anazmy** [comment]
Thanks, I did a test earlier to move to Python3 and it wasn't hard, and I intend to keep it that way, till Python3 becomes the norm.

**Comment by ghost** [comment]
Ok, I think 2.7 is still more common among distros. Codebase is still small, so moving to Python3 takes one afternoon:) Lets keep it 2.7 for now..
