### ISSUE TITLE
Add new page on Wiki

### ISSUE THREAD

**Issue by Dryusdan** [aker-gateway/Aker#73]
Hello
I don't found how to create pull request in wiki, so I attach file here.

I use your solution, and I tinker some tools next, so I share them with a tutorial. (Code are on [my github repo](https://github.com/Dryusdan/aker-autoinstaller/tree/master), If you want repatriate code on aker-gateway, tell me :)

[installation-of-aker-gateway-on-two-server-with-resilience.zip](https://github.com/aker-gateway/Aker/files/1796136/installation-of-aker-gateway-on-two-server-with-resilience.zip)

**Comment by anazmy** [comment]
That's really nice!
Many thanks @Dryusdan let me add this to the wiki

**Comment by anazmy** [comment]
Added : https://github.com/aker-gateway/Aker/wiki/installation-of-aker-gateway-on-two-server-with-resilience-by-Dryusdan

**Comment by Dryusdan** [comment]
Héhé, nice. I hope it's going to be used. :)

**Comment by anazmy** [comment]
I'm positive it will, many thanks again @Dryusdan

**Comment by Dryusdan** [comment]
You're welcome :)
